#! /bin/env bash

curl -X PUT localhost:3000/transactions/idZtpH3uiG \
     -H "Content-Type: application/json" \
     -d '{
           "name": "Test Transaction",
           "category": "Test Category",
           "members": ["Tom", "Dom"],
           "date": "2024-08-05",
           "expense_type": "expense",
           "paid": [200, 200],
           "currency": "USD",
           "ledger": "trap2",
           "weights": [0.5, 0.5]
         }'
