#! /bin/env bash

curl -X POST localhost:3000/recurrences \
     -H "Content-Type: application/json" \
     -d '{
           "name": "Test Transaction",
           "category": "Test Category",
           "members": ["Tom", "Dom"],
           "expense_type": "expense",
           "paid": [100, 200],
           "date": "2024-08-05",
           "currency": "USD",
           "ledger": "trap2",
           "weights": [0.5, 0.5],
           "rrule": "FREQ=WEEKLY;INTERVAL=1;COUNT=5"
         }'
